apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gomicroservicestarter-real
commonLabels:
  app: gomicroservicestarter-be
resources:
  - deployment.yaml
  - service.yaml
  - metricsservice.yaml
configMapGenerator:
  - name: config-backend
    literals:
      # - URL=http://pb-service:8080
      - LOGLEVEL=debug
