apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gomicroservicestarter-real
commonLabels:
  app: gomicroservicestarter-fe
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - metricsservice.yaml
secretGenerator:
  - name: db-user
    envs:
#- .env.creds
configMapGenerator:
  - name: config-frontend
    literals:
      - URL=http://gomicroservicestarter-service:8080
      - LOGLEVEL=debug
      # - SERVICEURL=10.42.1.232:8090
      - SERVICEURL=gomicroservicestarter-service-backend.go-microservice-starter.svc.cluster.local:8090
