apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gomicroservicestarter-servicemonitor-fe
  namespace: monitoring
  labels:
    name: gomicroservicestarter-servicemonitor-fe
spec:
  selector:
#    matchLabels:
#      app: gomicroservicestarter-fe
    matchExpressions:
      - { key: app, operator: In, values: [gomicroservicestarter-fe] }
  #      - {key: app, operator: In, values: [gomicroservicestarter-fe,gomicroservicestarter-be]}
  namespaceSelector:
    matchNames:
      - go-microservice-starter
  endpoints:
    - port: metrics
