apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gomicroservicestarter-servicemonitor
  namespace: monitoring
  labels:
    name: gomicroservicestarter-servicemonitor
spec:
  selector:
    matchLabels:
      app: gomicroservicestarter-fe
  namespaceSelector:
    matchNames:
      - go-microservice-starter
  endpoints:
    - port: metrics
